language: python
python:
  - "3.6"
  - "3.5"
  - "pypy3"
  - "2.7"
  - "pypy"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
before_install:
  - pip install -q django==$DJANGO_VERSION
install:
  - python setup.py develop
script:
  - python setup.py test
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO_VERSION=1.8
    - python: "pypy"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "pypy"
      env: DJANGO_VERSION=2.1
    - python: "2.7"
      env: DJANGO_VERSION=2.1
