#!/bin/bash

# Replace these three settings.
PROJDIR="/Users/panosl/web-projects/manishop.gr/manishop/manigifts"
PIDFILE="$PROJDIR/manishop.pid"
SOCKET="$PROJDIR/manishop.sock"

cd $PROJDIR
if [ -f $PIDFILE ]; then
	kill `cat -- $PIDFILE`
	rm -f -- $PIDFILE
fi

exec /usr/bin/env - \
	PYTHONPATH="../python:.." \
	./manage.py runfcgi socket=$SOCKET pidfile=$PIDFILE
